apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-generator
  namespace: default
  labels:
    app: image-generator
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-generator
  template:
    metadata:
      labels:
        app: image-generator
        version: v1
    spec:
      serviceAccountName: library-service-account
      containers:
        - name: image-generator
          image: 324547056370.dkr.ecr.us-east-1.amazonaws.com/image-generator:d15920458a4c96cdcd88690fb0108b25a46fbdaf
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: BASE_PATH
              value: "/image"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AGENT_RUNTIME_ARN
              value: "arn:aws:bedrock-agentcore:us-east-1:324547056370:runtime/diary_orchestrator_agent-90S9ctAFht"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
